server:
  port: 8080
  servlet:
    encoding:
      force-response: true
    session:
      timeout: 120m

spring:
  profiles :
    default : local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

mybatis:
  type-aliases-package: com.example.demo
  mapper-locations: mybatis/mapper/**/*.xml

jwt:
  header: Authorization
  # HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  secret: bWVkaWMtYmFja2VuZC1zcHJpbmctYm9vdC1qd3Qtc2VjcmV0fG1lZGljLWJhY2tlbmQtc3ByaW5nLWJvb3Qtand0LXNlY3JldHxtZWRpYy1iYWNrZW5kLXNwcmluZy1ib290LWp3dC1zZWNyZXQ=


#프로퍼티 암호화 설정
jasypt :
  encryptor :
    bean : jasyptStringEncryptor

---
spring:
  config :
    activate :
      on-profile : local
  servlet:
    multipart:
      location: C:/data/
      max-file-size: 10MB
      max-request-size: 150MB
  mvc :
    static-path-pattern: /static/**

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(hu+TIL8XKt9/gHHO4XOZHlaaZZmkZuqaIzmdRNiMab+82U49PzLhcXC5rZL5gmCc8cNPLOnYZYo=)
    username: ENC(c3WNE15lB7OkcJ65I+3kwg==)
    password: ENC(14puwc7gSE+XfSFxe1++AA==)
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 10
      maxLifetime: 1800000
      poolName: HikariCP
      readOnly: false
      connectionTestQuery: SELECT 1

logging:
  config:
    dir: /data/logs/demo
    file: demo
    level: DEBUG


file:
  dir: D:/data/upload/

